language: node_js

before_install:
- openssl aes-256-cbc -K $encrypted_b30536db7c50_key -iv $encrypted_b30536db7c50_iv -in token.deploy.json.enc -out token.deploy.json -d
- openssl aes-256-cbc -K $encrypted_9db652288906_key -iv $encrypted_9db652288906_iv -in settings.deploy.json.enc -out settings.deploy.json -d
- curl https://install.meteor.com/ | sh

script:
- meteor npm install
- npm run cli refresh-content
- meteor npm run lint
- meteor test --once --driver-package meteortesting:mocha

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: "meteor deploy --settings settings.deploy.json $METEORAPP_URL"
#   on:
#     branch: master
